# Generated by Django 5.1.7 on 2025-03-16 14:45

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.CharField(default=core.utils.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
